### ISSUE TITLE
Invalid channel for valid channels?

### ISSUE THREAD

**Issue by cwre** [Natenom/deaftoafk-for-mumo#2]
```
2016-06-15 13:41:14,748 DEBUG deaftoafk Deafened: Moved user 'cwrw' from channelid 0 into AFK.
2016-06-15 13:41:14,748 ERROR deaftoafk exception ::Murmur::InvalidChannelException
{
}
Traceback (most recent call last):
  File "/home/mumo/mumo/worker.py", line 115, in run
    res = fu(*args, **kwargs)
  File "modules/deaftoafk.py", line 206, in userStateChanged
    server.setState(state)
  File "/tmp/tmpSk1lvx.ice", line 2166, in setState
InvalidChannelException: exception ::Murmur::InvalidChannelException
{
}
```

This channel exists, but I don't know why it won't move me into it.

**Comment by cwre** [comment]
Channel ID was wrong, sorry.
